name: Testimonial
slug: testimonial
groups: content
form:
  general:

    - name: name

    - name: company
      help: Put designation and company name here. Eg, Creative Director, ThemeXpert 
      label: Job Title, Company Name

    - name: image
      type: file-manager

    - name: testimony
      type: editor
      value: Lorem ipsum dolor sit amet timeam deleniti mnesarchum ex sed alii hinc dolores ad cum. Urbanitas similique ex nam paulo temporibus ea vis id odio adhuc nostrum eos.

  styles:
    - name: image_style
      type: select
      value: square
      lable: Image Style 
      options:
        img-square : Square
        img-rounded: Rounded 
        img-circle : Circle

    - name: font
      type: typography

    - name: text_color
      type: color
      label: Text Color

    - name: bg_color
      type: color
      label: Background Color

    - name: margin
      type: margin

    - name: padding
      type: padding




