name: Testimonial Pro
slug: testimonial-pro
groups: content
form:
  general:
    - name: testimonials
      type: group-repeater
      schema: 
        - name: name
          value: John Doe

        - name: company
          help: Put designation and company name here. Eg, Creative Director, ThemeXpert 
          label: Job Title, Company Name

        - name: image
          type: file-manager

        - name: testimony
          type: editor
          value: Lorem ipsum dolor sit amet timeam deleniti mnesarchum ex sed alii hinc dolores ad cum. Urbanitas similique ex nam paulo temporibus ea vis id odio adhuc nostrum eos.
      value:
        - name: John Doe
          company: Creative Director, ThemeXpert
          testimony: Lorem ipsum dolor sit amet timeam deleniti mnesarchum ex sed alii hinc dolores ad cum. Urbanitas similique ex nam paulo temporibus ea vis id odio adhuc nostrum eos.
    
    - name: alignment
      type: select
      value: center
      label: Text Alignment
      options:
        left: Left
        right: Right
        center: Center
    - name: arrows
      type: switch
      value: true
      help: This setting allows you to turn the navigation arrows on or off.

    - name: dots
      type: switch
      label: Dots Navigation 
      value: false
      help: Disabling this option will remove the circle button at the bottom of the slider.

    - name: autoplay
      type: switch
      labe: Auto Play
      help: If you would like the slider to slide automatically, without the visitor having to click the next button.

    - name: autoplay_speed
      type: text
      label: Autoplay Speed 
      value: 5000
      help: Autoplay Speed in milliseconds
      depends:
        autoplay: true        
        
  styles:
    - name: image_style
      type: select
      value: square
      lable: Image Style 
      options:
        img-square : Square
        img-rounded: Rounded 
        img-circle : Circle

    - name: font
      type: typography
      label: Text Font

    - name: text_color
      type: color

    - name: name_font
      type: typography

    - name: name_color
      type: color

    - name: designation_font
      type: typography
      
    - name: designation_color
      type: color

    - name: bg_color
      type: color
      label: Background Color

    - name: nav_color
      type: color
      label: Navigation Arrow Color
      depends:
        arrows : true

    - name: margin
      type: margin
      value:
        top: 40px
        bottom: 40px
        left: 0px
        right: 0px

    - name: padding
      type: padding
      value:
        top: 0px
        bottom: 0px
        left: 40px
        right: 40px
